# Set this to true to get debug information in the console.
debug: false

# Database config
mysql:
  hostname: localhost
  port: 3306
  username: username
  password: password
  database: database

# How many lives all players get by default.
#
# This also defines the maximum amount of lives a player may have,
# unless they hold the permission 'sedexlives.maxlives.#' permission,
# where '#' is any number.
defaultLives: 3