name: Ouroboros
version: ${project.version}
main: com.github.salihbasicm.ouroboros.Ouroboros
author: Steinein_
description: Allows players to use lives in order to keep their inventory or XP.
api-version: "1.15"

softdepend: [PlaceholderAPI]

commands:
  lives:
    description: Main Ouroboros command
    usage: /<command>

permissions:
  ouroboros.use:
    description: Lets players use the Ouroboros system.
    default: op
  ouroboros.keepxp:
    description: Lets players keep their XP on death.
    default: op
  ouroboros.check:
    description: Lets players check their own lives.
    default: op
  ouroboros.check.others:
    description: Lets players check others' lives.
    default: op
  ouroboros.check.maxlives:
    description: Lets players check their own max lives.
    default: op
  ouroboros.check.maxlives.others:
    description: Lets players check others' lives.
    default: op
  ouroboros.set:
    description: Lets players set their own or others' lives.
    default: op
  ouroboros.maxlives:
    description: Defines the maximum amount of lives a player may have.
    default: op
  ouroboros.toggle:
    description: Toggles lives system on or off.
    default: op
  ouroboros.toggle.others:
    description: Toggle others' lives on or off.
    default: op
  ouroboros.item.add:
    description: Adds a new Ouroboros item
    default: op
  ouroboros.item.list:
    description: Lists Ouroboros items
    default: op
  ouroboros.item.get:
    description: Gets an Ouroboros item
    default: op
  ouroboros.item.remove:
    description: Removes an Ouroboros item
    default: op
  ouroboros.item.check:
    description: Checks an Ouroboros item for information
    default: op